use customer_behavior;

-- =====================================================================
-- Q1: What is the Total revenue generated by male vs female customers?
-- =====================================================================
SELECT gender, sum(purchase_amount) as total_revenue 
FROM customer
GROUP BY gender;

-- =====================================================================
--  Q2 What is the revenue contribution of each age group? 
-- =====================================================================
SELECT age_group, sum(purchase_amount) AS revenue
FROM customer
GROUP BY age_group
ORDER BY revenue DESC;

-- =======================================================================
-- Q3. Rank the products category with the highest average review ratings?
-- =======================================================================
SELECT category,
       ROUND(AVG(review_rating),1) AS rating,
       RANK() OVER (ORDER BY AVG(review_rating) DESC) AS rnk
FROM customer
GROUP BY category
ORDER BY rating DESC;

-- ============================================================================================================================
-- Q4. Do subscribed customers spend more? Compare average spend and total revenue between the subscribers and non-subscribers?
-- ============================================================================================================================
SELECT subscription_status, count(customer_id) AS Total_customers, 
round(avg(purchase_amount),2) AS avg_spend,
round(sum(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;

-- =============================================
-- Q5. Analyze purchase patterns across seasons?
-- =============================================
SELECT season, category, sum(purchase_amount) AS avg_spend
FROM customer
GROUP BY category, season
ORDER BY avg_spend DESC;

-- =======================================================
-- Q6. Examine which shipping types drive higher revenue.?
-- =======================================================
SELECT shipping_type, avg(purchase_amount) as revenue
FROM customer
GROUP BY shipping_type
ORDER BY revenue DESC;

-- =========================================================================================================================================================
-- Q7. Segment customers into new, returning, and loyal based on their total numbers of previous purchases and show the count of each segment and avg spend.
-- ========================================================================================================================================================= 
WITH customer_type AS (
    SELECT customer_id, previous_purchases, purchase_amount,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT 
    customer_segment, 
    COUNT(*) AS "Number of Customers", 
    avg(purchase_amount) AS avg_spend
FROM customer_type
GROUP BY customer_segment;

-- ==========================================================
-- Q8. Measure how discounts affect average purchase amounts?
-- ==========================================================
SELECT  discount_applied, count(*) AS num_transactions, avg(purchase_amount) AS avg_purchase_amount
FROM customer
GROUP BY discount_applied;